#pragma once
#include <Windows.h>

enum {
	WM_APP_WORKERREADY = WM_APP+1,
	WM_APP_WORKERFINISHED,
	WM_APP_WORKERERROR,
	WM_APP_WORKERCLICKED,
};

enum {
	WORKERERROR_NOERROR = 0,
	WORKERERROR_LBUTTONPRESSED,
	WORKERERROR_GETCURSORPOS,
	WORKERERROR_SETCURSORPOS,
};

#define WORKER_EXE_NAME L"AutoClickerWorker.exe"
